"""API route handlers organized by domain."""

from ai_flywheel.api.routers import (
    agents,
    blueprints,
    costs,
    deployments,
    discovery,
    embeddings,
    experiments,
    feedback,
    health,
    ingest,
    knowledge_graph,
    market,
    memory,
    ml,
    offers,
    patterns,
    policies,
    product,
    prompts,
    quality,
    reviews,
    thesis,
    tools,
    ventures,
    workflows,
)

__all__ = [
    "agents",
    "blueprints",
    "costs",
    "deployments",
    "discovery",
    "embeddings",
    "experiments",
    "feedback",
    "health",
    "ingest",
    "knowledge_graph",
    "market",
    "memory",
    "ml",
    "offers",
    "patterns",
    "policies",
    "product",
    "prompts",
    "quality",
    "reviews",
    "thesis",
    "tools",
    "ventures",
    "workflows",
]
